### ISSUE TITLE
Realizar módulo APE

### ISSUE THREAD

**Issue by vacagonzalo** [vacagonzalo/MSE-PDS-TP#6]
El módulo APE debe calcular el promedio de un registro de desplazamiento de N/2 valores de B bits.

El acumulador debe sumar el valor entrante y restar el valor saliente para evitar recalcular toda la ventana.

![APE](https://user-images.githubusercontent.com/7757903/189550150-f46b53a0-0321-40e8-a31d-dd3119cc0f0e.png)

Su entidad es:
* clk -> entrada: reloj
* ena -> entrada: habilitación
* rst -> entrada: reset (lógica negada)
* Xg -> entrada: valor ingresante
* Xd -> entrada: valor saliente
* S -> salida: promedio

Para finalizar el ticket se debe verificar el módulo.

**Comment by jonathancagua** [comment]
Listo, voy a seleccionar este modulo...

**Comment by vacagonzalo** [comment]
cuando crees tu branch que el nombre empiece con *6* (el número del issue)... por ejemplo: **6-ape-module**

**Comment by vacagonzalo** [comment]
y tus commits porfa que terminen con ". Ref #6".... por ejemplo **agrega acumulador. Ref #6**
